### PR TITLE
Fix for SDK calls to get custom and ext data

### LINKED ISSUE #67: Expose API for custom resources of profiles and services
For "custom resources" in ACS, there are currently 2 APIs being exposed:
* https://%tenantid%-adobeio.campaign.adobe.com/rest/customResources
* https://%tenantid%-adobeio.campaign.adobe.com/rest/profileAndServicesExt

In the SDK, we currently expose `getAllCustomResources()` method, which basically calls `/customResources` behind the scene. However we don't have any method for `/profileAndServicesExt`, which contains profile, services and linked customer resources.  

Therefore, we need to expose another method for `/profileAndServicesExt`, e.g. `getAllProfileCustomResources()`.

This will fix #60 .

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
Fixes #67 and #58 

## Description

Deprecated getAllCustomResources()
Added following sdk methods
getAllBasicCustomResources() calls - `/customResources/resourceType/<customResourceName>`
getAllProfileAndServicesExt() calls -` /profileAndServicesExt/{CUSTOMRESOURCE}`
getMetadataForResourceExt() - calls - `/profileAndServicesExt/resourceType/{RESOURCE}`

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -714,6 +739,59 @@ class CampaignStandardCoreAPI {
...
+  /**
+   * Get all Custom Resource records
+   *
+   * @param {string} resource one of profile, service, history
+   */
+  getAllBasicCustomResources (resource) {
+    const sdkDetails = { resource }
+
+    return new Promise((resolve, reject) => {
+      // TODO need to verify what all resource types are supported
```
Comment (shazron) [inline src/index.js:751]: can we verify this before the PR is merged in

File: src/index.js [hunk 2]
```diff
@@ -701,7 +726,7 @@ class CampaignStandardCoreAPI {
    */
   getAllCustomResources (customResource, parameters) {
     const sdkDetails = { customResource, parameters }
-
+    logger.warn('getAllCustomResources has been deprecated, use getAllProfileAndServicesExt()')
```
Comment (shazron) [inline src/index.js:729]: I think we should mention the two new functions. "use either X or Y". Your instruction is correct if they want the same behaviour, but not correct if they want what they think getAllCustomResources should do (if they never used it before). Same in the @deprecated notice

File: src/index.js [hunk 3]
```diff
@@ -688,6 +712,7 @@ class CampaignStandardCoreAPI {
 
   /**
    * Get all Custom Resource records
+   * @deprecated use getAllProfileAndServicesExt()
```
Comment (shazron) [inline src/index.js:715]: see comment below

**Review by shazron — CHANGES_REQUESTED** [review]

**Review by shazron — APPROVED** [review]
